### ISSUE TITLE
Paperless Filing download type

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-tax-lot-selector#16]
#### Description
Only download certain fields for Paperless filing workflow

**Comment by chriswhong** [comment]
The customer would like to see the following 4 columns in the downloaded csv/SHP:
 
User Input Borough
User Input Tax Block
User Input Tax Lot
Project
 
Project does not exist, but the ask is that we prepopulate it as an empty column, so when the user opens the CSV in excel (or whatever), the empty required column is waiting for them.

**Comment by allthesignals** [comment]
@chriswhong what is "User Input Borough"?

**Comment by allthesignals** [comment]
If the other option is "all", will a regular `SELECT *` work?

**Comment by chriswhong** [comment]
User Input Borough = `borocode` (1,2,3,4,5)
User Input Tax Block = `block`
User Input Tax Lot = `lot`

Yes, for the "all" option, `SELECT *` should be fine, though it will include `the_geom` & the_geom_webmercator` & `cartodb_id` in the CSV, so maybe a better user experience is eliminating these.  That would require explicitly stating all of the pluto columns, which we can do:  https://gist.github.com/chriswhong/f3e9de1cc894ee29661d12047b2b6540

**Comment by allthesignals** [comment]
@chriswhong thanks - those fields are already included.
