### ISSUE TITLE
can't select any lots

### ISSUE THREAD

**Issue by charlie-moffett** [NYCPlanning/labs-tax-lot-selector#23]
When using lotselector.planning.nyc.gov, I'm unable to select lots either by clicking on individual lots or by drawing a polygon.

I'm using Chrome 67 on Windows 10

**Comment by hannahkates** [comment]
Hi @charlie-moffett and @snphillips - thanks for flagging this issue. Have you still had trouble selecting lots recently? Also would you mind sharing a little info about how you've been using the app and for what type of projects? We primarily built the site for internal DCP use cases, so we're curious to understand who outside of DCP is using and how it we improve it - besides fixing browser compatibility :)
