### ISSUE TITLE
BUG:   {"error":["column \"exemptland\" does not exist"]}

### ISSUE THREAD

**Issue by adamshaul1** [NYCPlanning/labs-tax-lot-selector#30]
Tax Lot selected. All Pluto Data Selected.  Export to CSV selected.  
Instead of the Data Export, I received the following error message:
{"error":["column \"exemptland\" does not exist"]}

Occurred on a Chrome Browser and Dell Desktop

**Comment by paulsalama** [comment]
Received same error when attempting to download `All Pluto Data` as Shapefile.

Looks like `'exemptland'` needs to be removed from `https://github.com/NYCPlanning/labs-tax-lot-selector/blob/develop/js/scripts.js#L86` based on changes to PLUTO data dictionary.

**Comment by hannahkates** [comment]
Hi @paulsalama and @adamshaul1, this is resolved now. Thank you for documenting the problem!

**Comment by adamshaul1** [comment]
👍🏼 And thanks!

Best,

Adam Hanski
________________________________
