### ISSUE TITLE
Use DTM, not PLUTO

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-tax-lot-selector#6]
The DTM is updated more frequently (weekly on NYC open data).  This brings an ETL challenge, as bringing a dataset that large into carto is prone to a few issues.

The DTM can be downloaded here: https://data.cityofnewyork.us/Housing-Development/Department-of-Finance-Digital-Tax-Map/smk3-tmxj

**Comment by allthesignals** [comment]
Could set up a cron job in a dokku container that syncs large files through ogr and Carto's endpoint: https://carto.com/blog/data-sync-ogr

**Comment by chriswhong** [comment]
The trick is that the postGIS database is internal to the docker container that carto is running in, so you don't have the luxury of just doing regular database commands.  The import API, or the GUI are the only ways  in, and large files don't play well...

There are some workarounds where we can expose the database to the host machine... this would be worth looking into, but then you have to manually `cartodbfytable()` and stuff.

**Comment by chriswhong** [comment]
Actually, just downloaded the DTM... the polygons layer alone, zipped is 136MB, which might be manageable to send into the Carto import API.

**Comment by allthesignals** [comment]
I like the idea of exposing the internal database, or, even better, having that database running outside of the container on AWS or a Droplet (if it's ever rebuilt, all the data would be lost, no?).

Separately, maybe we just have a separate dokku app with a number of shell scripts triggered by crontab. Each script can bulk sync special cases like this. In this case, [the script might split the file into manageable pieces using ogr2ogr](https://gis.stackexchange.com/questions/195508/split-a-shapefile-into-smaller-files-on-linux-command-line).

**Comment by chriswhong** [comment]
Yes, it would be ideal to have the DB in a separate container altogether.  We would need to dedicate some time to getting this set up in production... it provides for both direct access to the DB for etl, and a more consistent upgrade path for the applications.
